print("Enter your name:")
name = input()
print("Hello, " + name + "!")
print("Enter your age:")
age = input()
print("You are " + age + " years old.")
print("Enter your favorite color:")
color = input()
print("Your favorite color is " + color + ".")
print("Enter your hometown:")
hometown = input()
print("Your hometown is " + hometown + ".")